services:
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
